-- ============================================================
-- 20260810_fix_4_1_duplicate_indexes.sql
--
-- Закрывает пункт 4 аудита AUDIT_2026-08-10.md (низкий приоритет):
-- «17 неиспользуемых индексов» — конкретно названные дубли.
--
-- ЧТО НАЗЫВАЛ АУДИТ
-- ------------------
--   • idx_rides_type + idx_rides_status «перекрываются с» idx_rides_type_status
--   • idx_notif_user «перекрывается с» idx_notif_user_unread
--   • idx_conv_users дублирует conversations_user1_id_user2_id_key
--
-- ПРОВЕРКА ПЕРЕД ПРИМЕНЕНИЕМ — И ПОЧЕМУ РЕШЕНИЕ ОБРАТНОЕ БУКВАЛЬНОМУ
-- ЧТЕНИЮ АУДИТА
-- ---------------------------------------------------------------------
-- По формальному правилу «левого префикса» составной индекс (type, status)
-- действительно мог бы заменить собой узкий индекс по одному type. Но
-- реальная статистика использования (pg_stat_user_indexes) на боевой базе
-- показала обратное:
--
--   idx_rides_type         — 249 сканирований
--   idx_rides_status       — 11 557 сканирований
--   idx_rides_type_status  — 0 сканирований (ни разу не использован)
--
--   idx_notif_user         — 384 сканирования
--   idx_notif_user_unread  — 0 сканирований
--
-- То есть в реальных запросах планировщик всегда выбирает узкие индексы
-- (по отдельности или через bitmap AND), а составные — ни разу. Причина
-- видна из кода: основной запрос ленты (Feed.tsx) фильтрует не простым
-- равенством по (type, status), а условием
--   .or('status.eq.active,and(status.eq.cancelled,cancelled_at.gte...)').eq('type', type)
-- — из-за OR по статусу простой составной индекс (type, status) для такого
-- запроса не подходит, и планировщик берёт узкие индексы. Уведомления
-- (MainLayout.tsx) фильтруются по (user_id, is_read) и отдельно по
-- (user_id, created_at) — без совместного упорядочивания по created_at
-- внутри is_read, которое давал бы idx_notif_user_unread.
--
-- Поэтому удалены именно составные (неиспользуемые) индексы, а не узкие
-- (активно используемые) — обратное тому, что можно прочитать в тексте
-- аудита буквально, но соответствует его же принципу «дубли перед
-- переносом стоит почистить»: реальный дубль — это то, что не используется
-- ни разу, а не то, что выглядит формально шире.
--
-- idx_conv_users / conversations_user1_id_user2_id_key — таблицы
-- conversations/messages/direct_messages удалены целиком раньше
-- (20260810_remove_internal_chat.sql, внутренний чат убран из проекта),
-- индексов на них уже нет — по этому пункту делать нечего.
--
-- ПРОВЕРЕНО НА БОЕВОЙ БАЗЕ (в транзакции с откатом)
-- ---------------------------------------------------
-- Индексы удалены, остальные индексы rides/notifications на месте
-- (idx_rides_status, idx_rides_type, idx_rides_creator, idx_rides_*,
-- idx_notif_user, idx_notifications_ride_id, оба pkey).
--
-- ОТКАТ
-- -----
--   CREATE INDEX idx_rides_type_status ON public.rides (type, status);
--   CREATE INDEX idx_notif_user_unread ON public.notifications (user_id, is_read, created_at DESC);
--
-- Миграция идемпотентна (DROP INDEX IF EXISTS).
-- ============================================================

DROP INDEX IF EXISTS public.idx_rides_type_status;
DROP INDEX IF EXISTS public.idx_notif_user_unread;
